import AppKit
import SwiftUI
import XCTest
@testable import Snaplet

/// Generates the images used in the README by rendering Snaplet's real views and
/// renderers, rather than assembling mock-ups in a design tool.
///
/// The subject matter is a synthetic desktop drawn here — Snaplet's own design,
/// not a screenshot of anyone else's product — so the images contain no personal
/// content and can be regenerated by anyone:
///
///     xcodebuild -project Snaplet.xcodeproj -scheme Snaplet \
///       -destination 'platform=macOS,arch=arm64' \
///       test -only-testing:SnapletTests/DocumentationScreenshotTests
///     cp /tmp/snaplet-docs/*.png docs/images/
@MainActor
final class DocumentationScreenshotTests: XCTestCase {

    private let directory = URL(fileURLWithPath: "/tmp/snaplet-docs")

    override func setUpWithError() throws {
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
    }

    private func write(_ image: CGImage, _ name: String) throws {
        let data = try ImageExporter.data(from: image, format: .png)
        try data.write(to: directory.appendingPathComponent("\(name).png"))
    }

    // MARK: - A stand-in desktop

    /// A neutral window and wallpaper of Snaplet's own design, used as something
    /// to capture. Deliberately generic: no other product is imitated.
    private func syntheticDesktop(width: Int, height: Int) -> CGImage {
        TestImages.make(width: width, height: height) { context in
            let colorSpace = CGColorSpace(name: CGColorSpace.sRGB)!
            let gradient = CGGradient(colorsSpace: colorSpace,
                                      colors: [NSColor(srgbRed: 0.16, green: 0.18, blue: 0.28, alpha: 1).cgColor,
                                               NSColor(srgbRed: 0.32, green: 0.24, blue: 0.40, alpha: 1).cgColor] as CFArray,
                                      locations: [0, 1])!
            context.drawLinearGradient(gradient,
                                       start: CGPoint(x: 0, y: CGFloat(height)),
                                       end: CGPoint(x: CGFloat(width), y: 0),
                                       options: [])

            context.translateBy(x: 0, y: CGFloat(height))
            context.scaleBy(x: 1, y: -1)
            let graphics = NSGraphicsContext(cgContext: context, flipped: true)
            NSGraphicsContext.saveGraphicsState()
            NSGraphicsContext.current = graphics

            let window = CGRect(x: CGFloat(width) * 0.10, y: CGFloat(height) * 0.12,
                                width: CGFloat(width) * 0.80, height: CGFloat(height) * 0.74)
            let shadow = NSShadow()
            shadow.shadowBlurRadius = 40
            shadow.shadowOffset = NSSize(width: 0, height: -12)
            shadow.shadowColor = NSColor.black.withAlphaComponent(0.4)
            NSGraphicsContext.saveGraphicsState()
            shadow.set()
            NSColor.white.setFill()
            NSBezierPath(roundedRect: window, xRadius: 14, yRadius: 14).fill()
            NSGraphicsContext.restoreGraphicsState()

            // Title bar with three neutral dots.
            let bar = CGRect(x: window.minX, y: window.minY, width: window.width, height: 38)
            NSGraphicsContext.saveGraphicsState()
            NSBezierPath(roundedRect: window, xRadius: 14, yRadius: 14).addClip()
            NSColor(white: 0.95, alpha: 1).setFill()
            NSBezierPath(rect: bar).fill()
            NSColor(white: 0.78, alpha: 1).setFill()
            for index in 0..<3 {
                NSBezierPath(ovalIn: CGRect(x: bar.minX + 18 + CGFloat(index) * 20,
                                            y: bar.midY - 5, width: 10, height: 10)).fill()
            }
            NSGraphicsContext.restoreGraphicsState()

            // Body: a heading, some paragraph rules and a token-looking line.
            let heading: [NSAttributedString.Key: Any] = [
                .font: NSFont.systemFont(ofSize: 26, weight: .semibold),
                .foregroundColor: NSColor(white: 0.13, alpha: 1)
            ]
            ("Deployment settings" as NSString).draw(at: NSPoint(x: window.minX + 32, y: bar.maxY + 26),
                                                     withAttributes: heading)
            NSColor(white: 0.86, alpha: 1).setFill()
            for row in 0..<5 {
                let y = bar.maxY + 78 + CGFloat(row) * 26
                let w = window.width - 64 - CGFloat((row * 37) % 160)
                NSBezierPath(roundedRect: CGRect(x: window.minX + 32, y: y, width: w, height: 10),
                             xRadius: 5, yRadius: 5).fill()
            }
            let mono: [NSAttributedString.Key: Any] = [
                .font: NSFont.monospacedSystemFont(ofSize: 15, weight: .regular),
                .foregroundColor: NSColor(srgbRed: 0.75, green: 0.22, blue: 0.32, alpha: 1)
            ]
            ("api_key = sk_live_0000000000000000" as NSString)
                .draw(at: NSPoint(x: window.minX + 32, y: bar.maxY + 220), withAttributes: mono)
            ("owner = ada@example.com" as NSString)
                .draw(at: NSPoint(x: window.minX + 32, y: bar.maxY + 248), withAttributes: mono)

            NSGraphicsContext.restoreGraphicsState()
        }
    }

    /// Renders a layer-backed view, including its sublayers.
    private func renderLayerBacked(_ view: NSView, size: CGSize) throws -> CGImage {
        view.frame = CGRect(origin: .zero, size: size)
        view.layoutSubtreeIfNeeded()
        view.layer?.layoutIfNeeded()

        let colorSpace = CGColorSpace(name: CGColorSpace.sRGB)!
        let context = try XCTUnwrap(CGContext(data: nil,
                                              width: Int(size.width * 2),
                                              height: Int(size.height * 2),
                                              bitsPerComponent: 8,
                                              bytesPerRow: 0,
                                              space: colorSpace,
                                              bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue))
        context.scaleBy(x: 2, y: 2)
        // A view that draws with a top-left origin renders upside down into a
        // plain bottom-up bitmap, so match its coordinate system first.
        if view.isFlipped {
            context.translateBy(x: 0, y: size.height)
            context.scaleBy(x: 1, y: -1)
        }
        if let layer = view.layer {
            layer.render(in: context)
        } else {
            let rep = try XCTUnwrap(view.bitmapImageRepForCachingDisplay(in: view.bounds))
            view.cacheDisplay(in: view.bounds, to: rep)
            if let image = rep.cgImage { context.draw(image, in: view.bounds) }
        }
        return try XCTUnwrap(context.makeImage())
    }

    // MARK: - The images

    func testGeneratesReadmeImages() throws {
        let displayPoints = CGSize(width: 1000, height: 640)
        let desktop = syntheticDesktop(width: Int(displayPoints.width * 2),
                                       height: Int(displayPoints.height * 2))
        let snapshot = DisplaySnapshot(displayID: 1,
                                       frame: CGRect(origin: .zero, size: displayPoints),
                                       scale: 2,
                                       image: desktop)

        try renderSelectionOverlay(snapshot: snapshot, size: displayPoints)
        try renderEditor(desktop: desktop)
        try renderStyling(desktop: desktop)
        print("DOCS IMAGES: \(directory.path)")
    }

    private func renderSelectionOverlay(snapshot: DisplaySnapshot, size: CGSize) throws {
        let view = SelectionOverlayView(snapshot: snapshot, mode: .area)
        let controller = SelectionOverlayController()
        view.controller = controller

        // The desktop is drawn in pixels; the overlay works in points with y
        // running up from the bottom, so the configuration lines sit here.
        let lineTopFromTop: CGFloat = 206      // "api_key = …"
        let lineBottomFromTop: CGFloat = 228   // below "owner = …"
        let top = size.height - lineTopFromTop
        let bottom = size.height - lineBottomFromTop

        controller.beginDrag(at: CGPoint(x: 112, y: top + 12))
        controller.updateDrag(to: CGPoint(x: 300, y: bottom - 8))

        view.frame = CGRect(origin: .zero, size: size)
        view.layoutSubtreeIfNeeded()

        // Put the cursor on an actual glyph so the loupe shows a real colour
        // instead of the white between letters. Scanning from the right also
        // keeps the loupe clear of the dimensions label.
        let rowFromTop: CGFloat = 211
        var cursor = CGPoint(x: 280, y: size.height - rowFromTop)
        for x in stride(from: CGFloat(285), to: CGFloat(150), by: -1) {
            let sampled = SelectionOverlayView.color(in: snapshot.image,
                                                     atX: Int(x * snapshot.scale),
                                                     y: Int(rowFromTop * snapshot.scale))
            if let sampled, sampled.redComponent > 0.5, sampled.blueComponent < 0.6,
               sampled.greenComponent < 0.5 {
                cursor = CGPoint(x: x, y: size.height - rowFromTop)
                break
            }
        }
        view.refresh(at: cursor)

        try write(try renderLayerBacked(view, size: size), "selection-overlay")
    }

    private func renderEditor(desktop: CGImage) throws {
        // Crop tightly around the content so the frame is not mostly empty.
        let crop = CGRect(x: 180, y: 120, width: 1560, height: 480)
        let cropped = try XCTUnwrap(desktop.cropping(to: crop))
        let document = EditorDocument(image: cropped, scale: 2, sourceURL: nil, capturedAt: Date())

        // Coordinates are in the cropped image's pixels: the heading sits near
        // the top, the two configuration lines about 290 px down.
        var box = Annotation(kind: .rectangle, frame: CGRect(x: 40, y: 84, width: 296, height: 48))
        box.lineWidth = 6
        document.annotations.append(box)

        var step = Annotation(kind: .step, frame: CGRect(x: 366, y: 82, width: 54, height: 54))
        step.number = 1
        document.annotations.append(step)

        var arrow = Annotation.line(kind: .arrow,
                                    from: CGPoint(x: 900, y: 170),
                                    to: CGPoint(x: 420, y: 292))
        arrow.lineWidth = 9
        document.annotations.append(arrow)

        // The point of the whole picture: the secret is covered.
        var redaction = Annotation(kind: .redaction,
                                   frame: CGRect(x: 46, y: 284, width: 336, height: 56))
        redaction.strokeColor = RGBAColor(red: 0.06, green: 0.06, blue: 0.07)
        document.annotations.append(redaction)

        let canvas = EditorCanvasView(document: document)
        try write(try renderLayerBacked(canvas, size: CGSize(width: 780, height: 240)), "editor")
    }

    private func renderStyling(desktop: CGImage) throws {
        // Crop to the window's body, not the window: Snaplet supplies the frame,
        // and two nested title bars would just look like a mistake.
        let content = try XCTUnwrap(desktop.cropping(to: CGRect(x: 202, y: 194, width: 1560, height: 440)))
        var preset = StylePreset.studio
        preset.title = "Deploy in one click"
        preset.subtitle = "Release notes · v2.4"
        let styled = try XCTUnwrap(PresentationRenderer.render(content: content,
                                                              style: preset,
                                                              maxLongestEdge: 1600))
        try write(styled, "styling")
    }
}
