#!/usr/bin/env python3
"""Fills the Turkish entries of Snaplet's String Catalog.

Run after `scripts/sync-strings.sh` has extracted new keys from the source.
Keys that are pure symbols, numbers or product names are copied verbatim so the
catalog has no "new" state left behind.
"""
import json
import sys
from pathlib import Path

TR = {
  "": "",
  "%@ / %@": "%@ / %@",
  "%@ → %@": "%@ → %@",
  "%@, %@": "%@, %@",
  "%lld": "%lld",
  "%lld lines": "%lld satır",
  "%lld minutes %lld seconds": "%lld dakika %lld saniye",
  "%lld seconds": "%lld saniye",
  "%lld × %lld px": "%lld × %lld px",
  "%lld%%": "%%%lld",
  "%lld%% of the video height": "video yüksekliğinin %%%lld kadarı",
  "100%": "100%",
  "12 FPS": "12 FPS",
  "15 FPS": "15 FPS",
  "200%": "200%",
  "30 FPS": "30 FPS",
  "3s": "3sn",
  "480 px": "480 px",
  "50%": "50%",
  "5s": "5sn",
  "60 FPS": "60 FPS",
  "640 px": "640 px",
  "8 FPS": "8 FPS",
  "800 px": "800 px",
  "A recording is already in progress.": "Zaten süren bir kayıt var.",
  "About": "Hakkında",
  "About Snaplet": "Snaplet Hakkında",
  "Actual behavior": "Gerçekleşen davranış",
  "Add redaction": "Sansür ekle",
  "Add text": "Metin ekle",
  "Add zoom": "Yakınlaştırma ekle",
  "Added": "Eklendi",
  "All": "Tümü",
  "Already used by another application.": "Bu kısayol başka bir uygulama tarafından kullanılıyor.",
  "Angle": "Açı",
  "Annotate": "İşaretle",
  "Anything else worth adding": "Eklemek istediğiniz başka bir şey",
  "Appearance": "Görünüm",
  "Applied when you open the Style tab in the editor. Nothing is added to a plain capture.": "Düzenleyicideki Stil sekmesini açtığınızda uygulanır. Sade bir çekime hiçbir şey eklenmez.",
  "Arrow": "Ok",
  "Aspect ratio": "En boy oranı",
  "Audio": "Ses",
  "Authorisation header": "Yetkilendirme başlığı",
  "Background": "Arka plan",
  "Block size": "Blok boyutu",
  "Blur": "Bulanıklaştır",
  "Blur radius": "Bulanıklık yarıçapı",
  "Bottom left": "Sol alt",
  "Bottom right": "Sağ alt",
  "Bring to front": "Öne getir",
  "Bug report": "Hata raporu",
  "Callout": "Açıklama balonu",
  "Camera": "Kamera",
  "Cancel": "Vazgeç",
  "Caption": "Başlık ve açıklama",
  "Capture Area": "Alan Yakala",
  "Capture Full Screen": "Tam Ekran Yakala",
  "Capture Window": "Pencere Yakala",
  "Capture failed: %@": "Yakalama başarısız: %@",
  "Capture instantly. Explain clearly. Share beautifully.": "Anında yakala. Net anlat. Güzel paylaş.",
  "Captured image, %@. Drag to copy the file.": "Yakalanan görüntü, %@. Dosyayı kopyalamak için sürükleyin.",
  "Captures you save appear here, searchable by file name and by any text Snaplet recognised in them.": "Kaydettiğiniz çekimler burada görünür; dosya adına ve Snaplet'in tanıdığı metne göre aranabilir.",
  "Captures, edits, OCR and exports all happen on this Mac. Snaplet has no account, no telemetry and makes no network requests.": "Çekim, düzenleme, metin tanıma ve dışa aktarma bu Mac üzerinde yapılır. Snaplet'te hesap ve telemetri yoktur; hiçbir ağ isteği göndermez.",
  "Choose image…": "Görsel seç…",
  "Choose…": "Seç…",
  "Circle": "Daire",
  "Clean": "Sade",
  "Clear": "Temizle",
  "Close": "Kapat",
  "Clear history and text index…": "Geçmişi ve metin dizinini temizle…",
  "Clear the history and recognised-text index?": "Geçmiş ve tanınan metin dizini temizlensin mi?",
  "Clearing the history removes Snaplet's records only. Your image and video files are left untouched.": "Geçmişi temizlemek yalnızca Snaplet'in kayıtlarını siler. Görüntü ve video dosyalarınıza dokunulmaz.",
  "Click a window to capture it · Esc to cancel": "Yakalamak için bir pencereye tıklayın · İptal için Esc",
  "Click highlighting is drawn by the system capture pipeline. Snaplet does not read keyboard input.": "Tıklama vurgusu sistemin yakalama katmanı tarafından çizilir. Snaplet klavye girdisi okumaz.",
  "Close preview": "Önizlemeyi kapat",
  "Colour": "Renk",
  "Constrain to a square": "Kareye sabitle",
  "Copied %lld lines of text.": "%lld satır metin kopyalandı.",
  "Copied to clipboard": "Panoya kopyalandı",
  "Copy": "Kopyala",
  "Copy Again": "Yeniden Kopyala",
  "Copy Markdown": "Markdown'ı Kopyala",
  "Copy Text on Screen": "Ekrandaki Metni Kopyala",
  "Copy all": "Tümünü kopyala",
  "Copy captures to the clipboard": "Çekimleri panoya kopyala",
  "Copy selected": "Seçilenleri kopyala",
  "Corner": "Köşe",
  "Corner radius": "Köşe yuvarlaklığı",
  "Could not start recording: %@": "Kayıt başlatılamadı: %@",
  "Could not write the file: %@": "Dosya yazılamadı: %@",
  "Countdown": "Geri sayım",
  "Create Bug Report": "Hata Raporu Oluştur",
  "Create Bug Report…": "Hata Raporu Oluştur…",
  "Crop": "Kırp",
  "Cut": "Kes",
  "Dark": "Koyu",
  "Default": "Varsayılan",
  "Default presentation style": "Varsayılan sunum stili",
  "Delete": "Sil",
  "Delete this preset": "Bu hazır ayarı sil",
  "Describe this step": "Bu adımı anlatın",
  "Docs": "Dokümantasyon",
  "Double-click to edit": "Düzenlemek için çift tıklayın",
  "Drag on the image, then press Return to apply.": "Görüntü üzerinde sürükleyin, sonra uygulamak için Return'e basın.",
  "Drag on the video to place it": "Yerleştirmek için video üzerinde sürükleyin",
  "Drag to select · Space to move · ⇧ square · ⌥ from center · Esc to cancel": "Sürükleyerek seçin · Taşımak için Boşluk · ⇧ kare · ⌥ merkezden · İptal için Esc",
  "Draw": "Serbest çiz",
  "Draw from the centre": "Merkezden çiz",
  "Drawing": "Çizim",
  "Edit": "Düzenle",
  "Edit Clipboard Image": "Panodaki Görseli Düzenle",
  "Editing canvas": "Düzenleme tuvali",
  "Ellipse": "Elips",
  "Email address": "E-posta adresi",
  "End here": "Burada bitir",
  "English": "English",
  "Environment": "Ortam bilgileri",
  "Everything below stays on this Mac. Snaplet does not connect to GitHub and does not upload anything.": "Aşağıdaki her şey bu Mac'te kalır. Snaplet GitHub'a bağlanmaz ve hiçbir şey yüklemez.",
  "Expected behavior": "Beklenen davranış",
  "Export GIF…": "GIF Dışa Aktar…",
  "Export Here": "Buraya Aktar",
  "Export MP4…": "MP4 Dışa Aktar…",
  "Export cancelled.": "Dışa aktarma iptal edildi.",
  "Export failed: %@": "Dışa aktarma başarısız: %@",
  "Export folder…": "Klasör olarak dışa aktar…",
  "Exported to %@.": "%@ klasörüne aktarıldı.",
  "Exporting copies these files next to the Markdown so you can drag them into the issue yourself.": "Dışa aktarma bu dosyaları Markdown'ın yanına kopyalar; issue'ya kendiniz sürükleyebilirsiniz.",
  "Exporting video…": "Video dışa aktarılıyor…",
  "Exports with a transparent background (PNG only).": "Saydam arka planla dışa aktarılır (yalnızca PNG).",
  "Export…": "Dışa Aktar…",
  "Favourite": "Favori",
  "Favourites only": "Yalnızca favoriler",
  "Fill colour": "Dolgu rengi",
  "Fill shapes": "Şekilleri doldur",
  "Fit": "Sığdır",
  "Font size": "Yazı boyutu",
  "Format": "Biçim",
  "Frame rate": "Kare hızı",
  "Free up space or choose a different output folder in Settings.": "Yer açın veya Ayarlar'dan farklı bir çıktı klasörü seçin.",
  "From": "Başlangıç",
  "GIF": "GIF",
  "GIF export is limited to the first %lld seconds of the trimmed range.": "GIF dışa aktarma, kırpılmış aralığın ilk %lld saniyesiyle sınırlıdır.",
  "General": "Genel",
  "Global shortcuts": "Genel kısayollar",
  "Gradient": "Gradyan",
  "Granted": "Verildi",
  "Hiding sensitive content": "Hassas içeriği gizleme",
  "Hide Snaplet": "Snaplet'i Gizle",
  "Highlight": "Vurgula",
  "Highlight mouse clicks": "Fare tıklamalarını vurgula",
  "History": "Geçmiş",
  "History is turned off": "Geçmiş kapalı",
  "History is unavailable": "Geçmiş kullanılamıyor",
  "History stores file paths, sizes and recognised text on this Mac. The media itself stays in your output folder — Snaplet never copies it into a database.": "Geçmiş; dosya yollarını, boyutları ve tanınan metni bu Mac'te saklar. Medyanın kendisi çıktı klasörünüzde kalır — Snaplet onu bir veritabanına kopyalamaz.",
  "History…": "Geçmiş…",
  "Hold Space": "Boşluğu basılı tutun",
  "IP address": "IP adresi",
  "Image": "Görüntü",
  "Images": "Görüntüler",
  "Include a webcam overlay": "Webcam katmanı ekle",
  "JPEG quality": "JPEG kalitesi",
  "Keep a local history of captures": "Çekimlerin yerel geçmişini tut",
  "Key-like string": "Anahtar benzeri dizi",
  "Keyboard Shortcuts…": "Klavye Kısayolları…",
  "Language": "Dil",
  "Language changes take effect the next time Snaplet starts.": "Dil değişikliği Snaplet'in bir sonraki açılışında etkili olur.",
  "Layout": "Yerleşim",
  "Library": "Kitaplık",
  "Light": "Açık",
  "Line": "Çizgi",
  "List the media in the report": "Medyayı raporda listele",
  "Long number": "Uzun numara",
  "MIT licensed.": "MIT lisanslıdır.",
  "Magnification: %@": "Büyütme: %@",
  "Magnifier": "Büyüteç",
  "Markdown copied to the clipboard.": "Markdown panoya kopyalandı.",
  "Match system": "Sistemle aynı",
  "Media": "Medya",
  "Microphone": "Mikrofon",
  "Midnight": "Gece",
  "Minimise": "Simge Durumuna Küçült",
  "Missing": "Bulunamadı",
  "More actions": "Diğer işlemler",
  "Move file to Trash…": "Dosyayı Çöp Kutusu'na taşı…",
  "Move the selection": "Seçimi taşı",
  "Move this file to the Trash?": "Bu dosya Çöp Kutusu'na taşınsın mı?",
  "Move to Trash": "Çöp Kutusu'na taşı",
  "My style": "Benim stilim",
  "Name": "Ad",
  "Needs at least one of ⌘, ⌥ or ⌃.": "⌘, ⌥ veya ⌃ tuşlarından en az biri gerekir.",
  "New annotations": "Yeni işaretlemeler",
  "Next number: %lld": "Sonraki numara: %lld",
  "No display or window is available to capture.": "Yakalanacak ekran veya pencere yok.",
  "No image chosen": "Görsel seçilmedi",
  "No matches": "Eşleşme yok",
  "No measurements recorded in this session yet.": "Bu oturumda henüz ölçüm kaydedilmedi.",
  "No media attached.": "Ekli medya yok.",
  "No recording is in progress.": "Süren bir kayıt yok.",
  "No text found in that area.": "Bu alanda metin bulunamadı.",
  "No text was recognised in this image.": "Bu görüntüde metin tanınmadı.",
  "None": "Yok",
  "Not Now": "Şimdi Değil",
  "Not granted": "Verilmedi",
  "Not set": "Atanmadı",
  "Nothing here yet": "Burada henüz bir şey yok",
  "OK": "Tamam",
  "Off": "Kapalı",
  "Only what you tick is included. Your computer name, account name and file paths are never added.": "Yalnızca işaretledikleriniz eklenir. Bilgisayar adınız, kullanıcı adınız ve dosya yollarınız asla eklenmez.",
  "Open History…": "Geçmişi Aç…",
  "Open Snaplet at login": "Girişte Snaplet'i aç",
  "Open System Settings": "Sistem Ayarları'nı Aç",
  "Open System Settings › Privacy & Security › Camera and enable Snaplet.": "Sistem Ayarları › Gizlilik ve Güvenlik › Kamera bölümünü açıp Snaplet'i etkinleştirin.",
  "Open System Settings › Privacy & Security › Microphone and enable Snaplet.": "Sistem Ayarları › Gizlilik ve Güvenlik › Mikrofon bölümünü açıp Snaplet'i etkinleştirin.",
  "Open System Settings › Privacy & Security › Screen & System Audio Recording and enable Snaplet.": "Sistem Ayarları › Gizlilik ve Güvenlik › Ekran ve Sistem Sesi Kaydı bölümünü açıp Snaplet'i etkinleştirin.",
  "Open…": "Aç…",
  "Original": "Orijinal",
  "Output folder": "Çıktı klasörü",
  "Padding": "Boşluk",
  "Pattern matching over the recognised text. It will miss things and it will flag harmless ones, so review each suggestion — nothing is hidden until you say so.": "Tanınan metin üzerinde örüntü eşleştirme yapılır. Bazı şeyleri kaçırır, zararsız olanları da işaretleyebilir; bu yüzden her öneriyi gözden geçirin — siz onaylamadan hiçbir şey gizlenmez.",
  "Paste": "Yapıştır",
  "Pause": "Duraklat",
  "Pixelate": "Pikselleştir",
  "Play": "Oynat",
  "Play a sound when a capture succeeds": "Çekim başarılı olduğunda ses çal",
  "Possibly sensitive": "Hassas olabilir",
  "Preparing…": "Hazırlanıyor…",
  "Preset": "Hazır ayar",
  "Press keys…": "Tuşlara basın…",
  "Press ⌫ while recording to unbind a shortcut. Snaplet's defaults use ⌃⌥⌘ so they do not collide with the built-in macOS screenshot shortcuts.": "Kayıt sırasında ⌫ tuşuna basarak bir kısayolu kaldırabilirsiniz. Snaplet varsayılanları ⌃⌥⌘ kullanır; böylece macOS'un yerleşik ekran görüntüsü kısayollarıyla çakışmaz.",
  "Preview": "Önizleme",
  "Quit Snaplet": "Snaplet'ten Çık",
  "Reading text…": "Metin okunuyor…",
  "Recognition runs on this Mac with Apple's Vision framework. Nothing is sent anywhere.": "Tanıma bu Mac'te Apple'ın Vision çatısıyla çalışır. Hiçbir yere veri gönderilmez.",
  "Record Area…": "Alanı Kaydet…",
  "Record Screen": "Ekranı Kaydet",
  "Record Window…": "Pencereyi Kaydet…",
  "Record microphone": "Mikrofonu kaydet",
  "Record system audio": "Sistem sesini kaydet",
  "Recording": "Kayıt",
  "Recording starts in %lld seconds": "Kayıt %lld saniye içinde başlıyor",
  "Recording stopped because of a write error: %@": "Yazma hatası nedeniyle kayıt durdu: %@",
  "Recording, %@": "Kaydediliyor, %@",
  "Rectangle": "Dikdörtgen",
  "Redact": "Sansürle",
  "Redact all suggestions": "Tüm önerileri sansürle",
  "Redact draws an opaque block and is the recommended choice. Blur and pixelate are visual effects: enough to keep a screenshot tidy, but not a guarantee against reconstruction. Whatever you choose, exporting rasterises the result — the original pixels are not written into the exported file.": "Sansür opak bir blok çizer ve önerilen seçenektir. Bulanıklaştırma ve pikselleştirme görsel efektlerdir: ekran görüntüsünü derli toplu tutar ama geri çevrilemezlik garantisi vermez. Hangisini seçerseniz seçin, dışa aktarma sonucu rasterize eder — orijinal pikseller dışa aktarılan dosyaya yazılmaz.",
  "Redaction": "Sansür",
  "Redo": "Yinele",
  "Refresh": "Yenile",
  "Remove from history": "Geçmişten kaldır",
  "Rendering frames…": "Kareler işleniyor…",
  "Repeat Last Area": "Son Alanı Tekrarla",
  "Reset crop": "Kırpmayı sıfırla",
  "Reset to full image": "Tüm görüntüye döndür",
  "Resolution": "Çözünürlük",
  "Resolution limit": "Çözünürlük sınırı",
  "Restore default shortcuts": "Varsayılan kısayolları geri yükle",
  "Reveal": "Klasörü aç",
  "Rotate left": "Sola döndür",
  "Rotate right": "Sağa döndür",
  "Rounded rectangle": "Yuvarlatılmış dikdörtgen",
  "Save": "Kaydet",
  "Save as preset": "Hazır ayar olarak kaydet",
  "Save captures to a folder automatically": "Çekimleri otomatik olarak bir klasöre kaydet",
  "Save frame": "Kareyi kaydet",
  "Scan again": "Yeniden tara",
  "Scan image for text": "Görüntüde metin ara",
  "Screen & System Audio Recording": "Ekran ve Sistem Sesi Kaydı",
  "Screenshot output": "Ekran görüntüsü çıktısı",
  "Search names and recognised text": "Adlarda ve tanınan metinde ara",
  "Select": "Seç",
  "Select All": "Tümünü Seç",
  "Selected: %@": "Seçili: %@",
  "Selected: zoom": "Seçili: yakınlaştırma",
  "Selection cancelled.": "Seçim iptal edildi.",
  "Session measurements": "Oturum ölçümleri",
  "Settings…": "Ayarlar…",
  "Shadow": "Gölge",
  "Shape": "Şekil",
  "Share-ready styling": "Paylaşıma hazır stil",
  "Short description": "Kısa açıklama",
  "Shortcut could not be registered: %@": "Kısayol kaydedilemedi: %@",
  "Shortcuts": "Kısayollar",
  "Show favourites only": "Yalnızca favorileri göster",
  "Show in Finder": "Finder'da göster",
  "Show the pointer": "İmleci göster",
  "Show the preview panel after a capture": "Çekimden sonra önizleme panelini göster",
  "Size": "Boyut",
  "Snaplet": "Snaplet",
  "Snaplet Editor": "Snaplet Düzenleyici",
  "Snaplet History": "Snaplet Geçmişi",
  "Snaplet Settings": "Snaplet Ayarları",
  "Snaplet Shortcuts": "Snaplet Kısayolları",
  "Snaplet bug report": "Snaplet hata raporu",
  "Snaplet could not open its local history database. Captures still work; only the history list is affected.": "Snaplet yerel geçmiş veritabanını açamadı. Çekimler çalışmaya devam eder; yalnızca geçmiş listesi etkilenir.",
  "Snaplet needs Camera permission for the webcam overlay.": "Webcam katmanı için Snaplet'in Kamera iznine ihtiyacı var.",
  "Snaplet needs Microphone permission to record narration.": "Anlatım kaydetmek için Snaplet'in Mikrofon iznine ihtiyacı var.",
  "Snaplet needs Screen & System Audio Recording permission.": "Snaplet'in Ekran ve Sistem Sesi Kaydı iznine ihtiyacı var.",
  "Snaplet never upscales. A limit only applies when the source is larger.": "Snaplet asla büyütmez. Sınır yalnızca kaynak daha büyük olduğunda uygulanır.",
  "Social": "Sosyal",
  "Solid": "Düz renk",
  "Something went wrong.": "Bir sorun oluştu.",
  "Start / Stop Recording": "Kaydı Başlat / Durdur",
  "Start Recording": "Kaydı Başlat",
  "Start here": "Burada başlat",
  "Starting in %lld": "%lld içinde başlıyor",
  "Step number": "Adım numarası",
  "Steps to reproduce": "Yeniden üretme adımları",
  "Stop Recording": "Kaydı Durdur",
  "Stop recording": "Kaydı durdur",
  "Studio": "Stüdyo",
  "Style": "Stil",
  "System": "Sistem",
  "System error %lld.": "Sistem hatası %lld.",
  "Text": "Metin",
  "Text colour": "Metin rengi",
  "Text recognition failed: %@": "Metin tanıma başarısız: %@",
  "That data is not an image Snaplet can open.": "Bu veri Snaplet'in açabileceği bir görüntü değil.",
  "The block is drawn into every exported frame in this range, before any zoom is applied.": "Blok, bu aralıktaki dışa aktarılan her kareye, yakınlaştırmadan önce çizilir.",
  "The display used for this capture is no longer connected.": "Bu çekimde kullanılan ekran artık bağlı değil.",
  "The output volume is out of free space.": "Çıktı diskinde boş alan kalmadı.",
  "The overlay is composited into the exported file, not just shown on screen.": "Katman yalnızca ekranda gösterilmez; dışa aktarılan dosyaya da işlenir.",
  "The window being captured is no longer available.": "Yakalanan pencere artık kullanılabilir değil.",
  "Theme": "Tema",
  "Thickness": "Kalınlık",
  "This moves the actual file to the Trash. Removing an item from the history instead leaves the file where it is.": "Bu, dosyanın kendisini Çöp Kutusu'na taşır. Bunun yerine geçmişten kaldırmak dosyayı yerinde bırakır.",
  "Timeline": "Zaman çizelgesi",
  "Title": "Başlık",
  "To": "Bitiş",
  "Token": "Token",
  "Top left": "Sol üst",
  "Top right": "Sağ üst",
  "Trim": "Kırpma",
  "Trim end": "Kırpma bitişi",
  "Trim start": "Kırpma başlangıcı",
  "Trimmed length: %@": "Kırpılmış süre: %@",
  "Try a different search term, or clear the filters.": "Farklı bir arama terimi deneyin veya filtreleri temizleyin.",
  "Turn it on in Settings › Library to keep a local record of your captures.": "Çekimlerinizin yerel kaydını tutmak için Ayarlar › Kitaplık bölümünden açın.",
  "Turn this on to place the screenshot on a background with padding, rounded corners and an optional caption.": "Ekran görüntüsünü boşluk, yuvarlatılmış köşe ve isteğe bağlı başlıkla bir arka plana yerleştirmek için bunu açın.",
  "Türkçe": "Türkçe",
  "Undo": "Geri al",
  "Use Folder": "Klasörü Kullan",
  "Use Snaplet for a moment, then refresh.": "Snaplet'i biraz kullanın, sonra yenileyin.",
  "Version %@": "Sürüm %@",
  "Video": "Video",
  "Video preview": "Video önizlemesi",
  "Videos": "Videolar",
  "Webcam overlay": "Webcam katmanı",
  "While selecting": "Seçim sırasında",
  "Width": "Genişlik",
  "Window": "Pencere",
  "Window frame": "Pencere çerçevesi",
  "Your capture files stay where they are.": "Çekim dosyalarınız olduğu yerde kalır.",
  "Zoom": "Yakınlaştırma",
  "that file is no longer on disk": "bu dosya artık diskte değil",
  "·": "·",
}


def main() -> int:
    check_only = "--check" in sys.argv
    path = Path(__file__).resolve().parent.parent / "Snaplet/Resources/Localizable.xcstrings"
    catalog = json.loads(path.read_text())
    strings = catalog["strings"]

    if check_only:
        untranslated = []
        for key, entry in strings.items():
            unit = entry.get("localizations", {}).get("tr", {}).get("stringUnit", {})
            if unit.get("state") != "translated" or "value" not in unit:
                untranslated.append(key)
        if untranslated:
            print(f"{len(untranslated)} of {len(strings)} keys have no Turkish translation:")
            for key in sorted(untranslated):
                print(f"  {key!r}")
            print("Run ./scripts/sync-strings.sh and add the missing text to scripts/turkish_strings.py")
            return 1
        print(f"all {len(strings)} keys are translated into Turkish")
        return 0

    missing = []
    for key, entry in strings.items():
        translation = TR.get(key)
        if translation is None:
            missing.append(key)
            continue
        localizations = entry.setdefault("localizations", {})
        localizations["tr"] = {
            "stringUnit": {"state": "translated", "value": translation}
        }
        # Mark the source language explicitly so nothing is left in "new".
        localizations.setdefault("en", {
            "stringUnit": {"state": "translated", "value": key}
        })
        entry.pop("shouldTranslate", None)

    path.write_text(json.dumps(catalog, indent=2, ensure_ascii=False, sort_keys=True) + "\n")

    unused = sorted(set(TR) - set(strings))
    print(f"translated {len(strings) - len(missing)} of {len(strings)} keys")
    if missing:
        print("MISSING Turkish translations:")
        for key in sorted(missing):
            print(f"  {key!r}")
    if unused:
        print("Stale entries (no longer in the catalog):")
        for key in unused:
            print(f"  {key!r}")
    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(main())
